project:
  type: book

book:
  title: "Interpreting Machine Learning Models With SHAP"
  subtitle: "A Guide With Python Examples And Theory On Shapley Values"
  author: "Christoph Molnar"
  output-file: shap
  chapters:
    - index.qmd
    - introduction.qmd
    - history.qmd
    - theory-shapley.qmd
    - shapley-to-shap.qmd
    - estimation-overview.qmd
    - linear.qmd
    - logistic.qmd
    - additive.qmd
    - interactions.qmd
    - correlation.qmd
    - regression.qmd
    - image.qmd
    - image-deepexplainer.qmd
    - text.qmd
    - limitations.qmd
    - dashboard.qmd  
    - alternative-libraries.qmd
    - extensions.qmd
    - other.qmd
    - acknowledgments.qmd
    - advertisement.qmd
    - references.qmd
  appendices:
    - estimation.qmd
    - maskers.qmd

execute:
  cache: true
  warning: false

bibliography: references.bib
cite-method: citeproc
csl: aquatic-sciences

format:
  epub:
    html-math-method: mathml
    lang: en-US
    date: "2023-08-01"
  pdf:
    documentclass: scrbook
    highlight-style: nord
    toc: true
    toc-depth: 2
    number-depth: 2
    toc-title: "Content"
    lof: false
    lot: false
    color-links: true
    links-as-notes: true
    citecolor: "blue"
