on:
  workflow_dispatch:
  push:
    branches: render

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Install system dependencies
        run: |
          brew install cmake libomp

      - name: Install Python and Deps
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          pip install wheel
          pip install jupyter
          pip install -r manuscript/requirements.txt 

      - name: Render
        continue-on-error: true
        run: |
          cd manuscript
          git rev-parse --short HEAD > latex/hash.tex
          quarto render --profile leanpub --to pdf
          mv _book/shap.pdf ./
          quarto render --profile leanpub --to epub
          mv shap.pdf _book/

      - name: Show logs and files on failure
        if: failure()
        run: |
          echo "Rendering failed. Showing contents of manuscript directory:"
          ls -la manuscript
          echo "Displaying log files, if any:"
          find manuscript -name "*.log" -exec cat {} +
          if [ -f manuscript/index.log ]; then
            echo "Displaying contents of index.log:"
            cat manuscript/index.log
          else
            echo "index.log not found."
          fi

      - name: Publish
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./manuscript/_book

