on:
  workflow_dispatch:
  push:
    branches: render

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4  # Actualiza a la versión v4 de actions/checkout
        with:
          fetch-depth: 0  # Esto asegura que todos los commits estén disponibles para Quarto

      - name: Set up Python
        uses: actions/setup-python@v4  # Actualiza a la versión v3 de actions/setup-python
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Install wheel
        run: python -m pip install wheel

      - name: Install lightgbm dependencies
        run: brew install cmake

      - run: pip install jupyter
      - run: pip install -r manuscript/requirements.txt

      - name: Render
        run: |
          cd manuscript
          git rev-parse --short HEAD > latex/hash.tex
          quarto render --profile leanpub --to pdf
          mv _book/shap.pdf ./
          quarto render --profile leanpub --to epub
          mv shap.pdf _book/

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./manuscript/_book
