on:
  workflow_dispatch:
  push:
    branches: render

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install system dependencies
        run: |
          brew install cmake libomp

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          pip install wheel
          pip install jupyter
          pip install -r manuscript/requirements.txt

      - name: Install TinyTeX
        run: |
          curl -fsSL https://yihui.org/tinytex/install-unx.sh | sh
          if [ -d "$HOME/.TinyTeX" ]; then
            sudo mv "$HOME/.TinyTeX" /opt/TinyTeX
            sudo /opt/TinyTeX/bin/*/tlmgr path add
          else
            echo "TinyTeX installation directory not found"
            exit 1
          fi
        shell: bash

      - name: Render
        run: |
          cd manuscript
          git rev-parse --short HEAD > latex/hash.tex
          quarto render --profile leanpub --to pdf
          mv _book/shap.pdf ./
          quarto render --profile leanpub --to epub
          mv shap.pdf _book/

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./manuscript/_book

