on:
  workflow_dispatch:
  push:
    branches: render

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Install TinyTeX
        run: |
          curl -fsSL https://yihui.org/tinytex/install-unx.sh | sh
          # Ensure the installation directory exists
          if [ -d "$HOME/Library/TinyTeX" ]; then
            echo "TinyTeX installed in $HOME/Library/TinyTeX"
            sudo mkdir -p /opt/TinyTeX
            sudo mv "$HOME/Library/TinyTeX" /opt/TinyTeX
            # List the contents of /opt/TinyTeX/bin to verify the correct path
            ls -la /opt/TinyTeX/bin
          else
            echo "TinyTeX installation directory not found in $HOME/Library/TinyTeX"
            ls -la $HOME/Library
            exit 1
          fi
          echo "TinyTeX moved to /opt/TinyTeX"

      - name: Verify TinyTeX installation
        run: |
          TINYTEX_BIN=$(find /opt/TinyTeX/bin -type f -name tlmgr)
          if [ -z "$TINYTEX_BIN" ]; then
            echo "tlmgr not found in /opt/TinyTeX/bin"
            ls -la /opt/TinyTeX/bin
            exit 1
          else
            echo "Using tlmgr from $TINYTEX_BIN"
            sudo "$TINYTEX_BIN" update --self
            "$TINYTEX_BIN" --version
            TINYTEX_DIR=$(dirname "$TINYTEX_BIN")
            echo "Adding $TINYTEX_DIR to PATH"
            export PATH="$TINYTEX_DIR:$PATH"
          fi

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install system dependencies
        run: |
          brew install cmake libomp

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          pip install wheel
          pip install jupyter
          pip install -r manuscript/requirements.txt

      - name: Render
        env:
          PATH: "/opt/TinyTeX/bin/x86_64-darwin:$PATH"
        run: |
          cd manuscript
          git rev-parse --short HEAD > latex/hash.tex
          quarto render --profile leanpub --to pdf
          mv _book/shap.pdf ./
          quarto render --profile lean

